### ISSUE TITLE
OmniROM 12.1 v2 (ARM64) Cannot install any apks

### ISSUE THREAD

**Issue by atsakir** [YAJATapps/android_device_allwinner_apollo-p2#1]
Trying to install any apk through Files gets hung in "Staging app...". This happens both from external drive and internal as well. Multiple different apks tried.  Also copying from external drive to SD appears to work successfully but on refresh of directory all copied files are gone

I suspect it is an SD card issue but will investigate further.

@edit: nevermind, I was using a very slow usb hub and Files didn't show copy progress. Once I managed to copy over to the local filesystem an apk with a better file manager and installed I could see that it was just very slow transfer speeds from the external drive that failed the installation

**Comment by YAJATapps** [comment]
Good to hear it worked with better hub
